import { Pool } from "pg";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env.local" });

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});

const INITIAL_SCHOOLS = [
  {
    slug: "gems-wellington-primary",
    name: "GEMS Wellington Primary School",
    type: "school",
    area: "Al Sufouh",
    curriculum: ["British"],
    phases: ["FS1", "FS2", "Primary"],
    khda_rating: "Outstanding",
    khda_rating_year: 2024,
    fee_min: 39000,
    fee_max: 64000,
    website: "https://gemswellingtonprimary.ae",
    has_sen_support: true,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    gender: "mixed",
  },
  {
    slug: "gems-world-academy",
    name: "GEMS World Academy",
    type: "school",
    area: "Al Barsha South",
    curriculum: ["IB"],
    phases: ["Primary", "Secondary"],
    khda_rating: "Outstanding",
    khda_rating_year: 2024,
    fee_min: 62000,
    fee_max: 102000,
    website: "https://gemsworldacademy-dubai.com",
    has_sen_support: true,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    has_swimming_pool: true,
    gender: "mixed",
  },
  {
    slug: "dubai-british-school-jbr",
    name: "Dubai British School Jumeirah Park",
    type: "school",
    area: "Jumeirah Park",
    curriculum: ["British"],
    phases: ["FS1", "FS2", "Primary", "Secondary"],
    khda_rating: "Very Good",
    khda_rating_year: 2024,
    fee_min: 42000,
    fee_max: 72000,
    website: "https://dubaibritishschool.ae",
    has_sen_support: true,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    gender: "mixed",
  },
  {
    slug: "kings-school-al-barsha",
    name: "Kings' School Al Barsha",
    type: "school",
    area: "Al Barsha",
    curriculum: ["British"],
    phases: ["FS1", "FS2", "Primary"],
    khda_rating: "Outstanding",
    khda_rating_year: 2024,
    fee_min: 47000,
    fee_max: 61000,
    website: "https://kings-edu.com",
    has_sen_support: true,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    has_swimming_pool: true,
    gender: "mixed",
  },
  {
    slug: "dubai-college",
    name: "Dubai College",
    type: "school",
    area: "Al Sufouh",
    curriculum: ["British"],
    phases: ["Secondary", "Sixth Form"],
    khda_rating: "Outstanding",
    khda_rating_year: 2024,
    fee_min: 82000,
    fee_max: 96000,
    website: "https://dubaicollege.org",
    has_sen_support: true,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    has_swimming_pool: true,
    gender: "mixed",
  },
  {
    slug: "repton-school-dubai",
    name: "Repton School Dubai",
    type: "school",
    area: "Nad Al Sheba",
    curriculum: ["British", "IB"],
    phases: ["FS1", "FS2", "Primary", "Secondary", "Sixth Form"],
    khda_rating: "Outstanding",
    khda_rating_year: 2024,
    fee_min: 49000,
    fee_max: 93000,
    website: "https://reptondubai.org",
    has_sen_support: true,
    has_transport: true,
    has_boarding: true,
    has_after_school: true,
    has_sports_facilities: true,
    has_swimming_pool: true,
    has_arts_program: true,
    gender: "mixed",
  },
  {
    slug: "jumeirah-english-speaking-school",
    name: "Jumeirah English Speaking School (JESS)",
    type: "school",
    area: "Arabian Ranches",
    curriculum: ["British"],
    phases: ["FS1", "FS2", "Primary", "Secondary"],
    khda_rating: "Outstanding",
    khda_rating_year: 2024,
    fee_min: 52000,
    fee_max: 78000,
    website: "https://jess.sch.ae",
    has_sen_support: true,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    has_swimming_pool: true,
    gender: "mixed",
  },
  {
    slug: "dubai-international-academy",
    name: "Dubai International Academy",
    type: "school",
    area: "Emirates Hills",
    curriculum: ["IB"],
    phases: ["Primary", "Secondary"],
    khda_rating: "Very Good",
    khda_rating_year: 2024,
    fee_min: 53000,
    fee_max: 88000,
    website: "https://diadubai.com",
    has_sen_support: true,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    gender: "mixed",
  },
  {
    slug: "gems-modern-academy",
    name: "GEMS Modern Academy",
    type: "school",
    area: "Nad Al Sheba",
    curriculum: ["Indian"],
    phases: ["Primary", "Secondary"],
    khda_rating: "Outstanding",
    khda_rating_year: 2024,
    fee_min: 18000,
    fee_max: 24000,
    website: "https://gemsmodernacademy.com",
    has_sen_support: true,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    gender: "mixed",
  },
  {
    slug: "indian-high-school-dubai",
    name: "The Indian High School",
    type: "school",
    area: "Oud Metha",
    curriculum: ["Indian"],
    phases: ["Primary", "Secondary"],
    khda_rating: "Good",
    khda_rating_year: 2024,
    fee_min: 8000,
    fee_max: 12000,
    website: "https://ihsdubai.org",
    has_sen_support: false,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    gender: "mixed",
  },
  {
    slug: "american-school-dubai",
    name: "American School of Dubai",
    type: "school",
    area: "Al Barsha",
    curriculum: ["American"],
    phases: ["Primary", "Secondary"],
    khda_rating: "Outstanding",
    khda_rating_year: 2024,
    fee_min: 65000,
    fee_max: 98000,
    website: "https://asdubai.org",
    has_sen_support: true,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    has_swimming_pool: true,
    has_arts_program: true,
    gender: "mixed",
  },
  {
    slug: "gems-new-millennium-school",
    name: "GEMS New Millennium School",
    type: "school",
    area: "Al Khail",
    curriculum: ["Indian"],
    phases: ["Primary", "Secondary"],
    khda_rating: "Very Good",
    khda_rating_year: 2024,
    fee_min: 14000,
    fee_max: 20000,
    website: "https://gemsnms-alkhail.com",
    has_sen_support: true,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    gender: "mixed",
  },
  {
    slug: "nord-anglia-international-school",
    name: "Nord Anglia International School Dubai",
    type: "school",
    area: "Al Barsha South",
    curriculum: ["British", "IB"],
    phases: ["FS1", "FS2", "Primary", "Secondary"],
    khda_rating: "Very Good",
    khda_rating_year: 2024,
    fee_min: 55000,
    fee_max: 95000,
    website: "https://nasdubai.com",
    has_sen_support: true,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    has_swimming_pool: true,
    has_arts_program: true,
    gender: "mixed",
  },
  {
    slug: "raffles-nursery-marina",
    name: "Raffles Nursery Marina",
    type: "nursery",
    area: "Dubai Marina",
    curriculum: ["British"],
    phases: ["FS1", "FS2"],
    khda_rating: "Very Good",
    khda_rating_year: 2024,
    fee_min: 28000,
    fee_max: 42000,
    website: "https://rafflesnursery.com",
    has_sen_support: true,
    has_transport: false,
    has_after_school: false,
    has_sports_facilities: false,
    gender: "mixed",
  },
  {
    slug: "blossom-nursery-downtown",
    name: "Blossom Nursery Downtown",
    type: "nursery",
    area: "Downtown Dubai",
    curriculum: ["British"],
    phases: ["FS1", "FS2"],
    khda_rating: "Good",
    khda_rating_year: 2024,
    fee_min: 25000,
    fee_max: 38000,
    website: "https://blossomnursery.com",
    has_sen_support: false,
    has_transport: false,
    has_after_school: false,
    has_sports_facilities: false,
    gender: "mixed",
  },
  {
    slug: "maple-bear-jlt",
    name: "Maple Bear Canadian Nursery JLT",
    type: "nursery",
    area: "JLT",
    curriculum: ["Canadian"],
    phases: ["FS1", "FS2"],
    khda_rating: "Good",
    khda_rating_year: 2024,
    fee_min: 22000,
    fee_max: 35000,
    website: "https://maplebeardubai.com",
    has_sen_support: false,
    has_transport: true,
    has_after_school: false,
    has_sports_facilities: false,
    gender: "mixed",
  },
  {
    slug: "kids-first-nursery-jumeirah",
    name: "Kids First Group Nursery Jumeirah",
    type: "nursery",
    area: "Jumeirah",
    curriculum: ["British"],
    phases: ["FS1", "FS2"],
    khda_rating: "Very Good",
    khda_rating_year: 2024,
    fee_min: 30000,
    fee_max: 45000,
    website: "https://kidsfirstgroup.com",
    has_sen_support: true,
    has_transport: true,
    has_after_school: false,
    has_sports_facilities: true,
    gender: "mixed",
  },
  {
    slug: "dubai-heights-academy",
    name: "Dubai Heights Academy",
    type: "school",
    area: "Al Barsha South",
    curriculum: ["American"],
    phases: ["FS1", "FS2", "Primary", "Secondary"],
    khda_rating: "Good",
    khda_rating_year: 2024,
    fee_min: 32000,
    fee_max: 54000,
    website: "https://dubaiheightsacademy.com",
    has_sen_support: true,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    gender: "mixed",
  },
  {
    slug: "gems-firstpoint-school",
    name: "GEMS FirstPoint School",
    type: "school",
    area: "The Villa",
    curriculum: ["British"],
    phases: ["FS1", "FS2", "Primary", "Secondary"],
    khda_rating: "Very Good",
    khda_rating_year: 2024,
    fee_min: 35000,
    fee_max: 55000,
    website: "https://gemsfirstpointschool.com",
    has_sen_support: true,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    has_swimming_pool: true,
    gender: "mixed",
  },
  {
    slug: "lycee-francais-international-georges-pompidou",
    name: "Lycee Francais International Georges Pompidou",
    type: "school",
    area: "Oud Metha",
    curriculum: ["French"],
    phases: ["Primary", "Secondary"],
    khda_rating: "Good",
    khda_rating_year: 2024,
    fee_min: 28000,
    fee_max: 52000,
    website: "https://lfigp.org",
    has_sen_support: true,
    has_transport: true,
    has_after_school: true,
    has_sports_facilities: true,
    gender: "mixed",
    languages: ["French", "English", "Arabic"],
  },
];

async function seed() {
  console.log("Seeding database...");

  for (const school of INITIAL_SCHOOLS) {
    try {
      await pool.query(
        `
        INSERT INTO schools (
          slug, name, type, area, curriculum, phases, khda_rating, khda_rating_year,
          fee_min, fee_max, website, has_sen_support, has_transport, has_after_school,
          has_sports_facilities, has_swimming_pool, has_boarding, has_arts_program,
          gender, languages
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
        ON CONFLICT (slug) DO UPDATE SET
          name = EXCLUDED.name,
          khda_rating = EXCLUDED.khda_rating,
          khda_rating_year = EXCLUDED.khda_rating_year,
          fee_min = EXCLUDED.fee_min,
          fee_max = EXCLUDED.fee_max,
          updated_at = NOW()
      `,
        [
          school.slug,
          school.name,
          school.type,
          school.area,
          school.curriculum,
          school.phases,
          school.khda_rating,
          school.khda_rating_year,
          school.fee_min,
          school.fee_max,
          school.website,
          school.has_sen_support,
          school.has_transport ?? false,
          school.has_after_school ?? false,
          school.has_sports_facilities ?? false,
          (school as Record<string, unknown>).has_swimming_pool ?? false,
          (school as Record<string, unknown>).has_boarding ?? false,
          (school as Record<string, unknown>).has_arts_program ?? false,
          school.gender || "mixed",
          (school as Record<string, unknown>).languages || ["English", "Arabic"],
        ]
      );
      console.log(`  Seeded: ${school.name}`);
    } catch (err) {
      console.error(`  Error seeding ${school.name}:`, err);
    }
  }

  console.log(`\nSeeded ${INITIAL_SCHOOLS.length} schools/nurseries`);
  await pool.end();
}

seed().catch(console.error);
